### ISSUE TITLE
Login Form Block - Styling Issue whereby the login fields overflow the container borders

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeedwp/lsx-design#212]
## Describe the bug
The form fields on the login section are extending beyond the intended border, causing a visual misalignment. The issue is occurring specifically on the Pro Portal Login page.

## To Reproduce
1. Go to [Pro Portal Login Page](https://deepblueadventures.lightspeedwp.dev/pro-portal/dashboard/)
2. Observe the Pro Portal Login form.
3. Notice that the form fields are overflowing the border instead of being contained properly.

## Expected behavior
The form fields should be properly aligned within the borders of the login form container. The fields should not extend outside of the defined box, and the padding should be consistent.

## Screenshots
A screenshot is provided to visually depict the issue. The fields are clearly spilling over the edges, causing the form to appear broken and poorly styled. 

![Screenshot](https://github.com/user-attachments/assets/1738c4d6-34f6-4714-b13b-08fe9adb007f)

## Desktop (please complete the following information):
- OS: [e.g. macOS]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

## Smartphone (please complete the following information):
- Device: [e.g. iPhone 12]
- OS: [e.g. iOS 14.4]
- Browser: [e.g. Safari]
- Version: [e.g. 14]

## Additional context
This issue affects user experience by making the login form visually unappealing and difficult to use, especially for new users. It also impacts the overall perception of professionalism on the site. Styling adjustments are required to contain the fields within the borders and ensure consistent padding and spacing.

**Comment by Justinabes007** [comment]
A fix in [PR #214](https://github.com/lightspeedwp/lsx-design/pull/214) to address the login form input overflow reported in this issue.

### Summary of Fix
The issue was resolved by applying `box-sizing: border-box;` to the form inputs within **form#loginform**. This adjustment ensures that padding and borders are included within the input elements’ defined width, preventing overflow outside of the form container.

### Key Changes
Updated CSS for form#loginform input to include:
`box-sizing: border-box;`
This change allows the inputs to stay within the container dimensions, providing a more consistent layout across various screen sizes and browsers.

### Testing
We tested the updated styling across multiple screen sizes and browsers to confirm that the inputs are now properly contained within the form.

Please review and let us know if any further adjustments are needed. Thank you!
